# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.GPSFrame = QtWidgets.QFrame(self.centralwidget)
        self.GPSFrame.setGeometry(QtCore.QRect(0, 130, 311, 291))
        self.GPSFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.GPSFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.GPSFrame.setObjectName("GPSFrame")
        self.GPSTextLog = QtWidgets.QPlainTextEdit(self.GPSFrame)
        self.GPSTextLog.setGeometry(QtCore.QRect(10, 30, 291, 251))
        self.GPSTextLog.setObjectName("GPSTextLog")
        self.GPSLabel = QtWidgets.QLabel(self.GPSFrame)
        self.GPSLabel.setGeometry(QtCore.QRect(20, 10, 47, 13))
        self.GPSLabel.setObjectName("GPSLabel")
        self.FPGAFrame = QtWidgets.QFrame(self.centralwidget)
        self.FPGAFrame.setGeometry(QtCore.QRect(320, 130, 311, 291))
        self.FPGAFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FPGAFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FPGAFrame.setObjectName("FPGAFrame")
        self.FPGATextLog = QtWidgets.QPlainTextEdit(self.FPGAFrame)
        self.FPGATextLog.setGeometry(QtCore.QRect(10, 30, 291, 251))
        self.FPGATextLog.setObjectName("FPGATextLog")
        self.FPGALabel = QtWidgets.QLabel(self.FPGAFrame)
        self.FPGALabel.setGeometry(QtCore.QRect(10, 10, 47, 13))
        self.FPGALabel.setObjectName("FPGALabel")
        self.ConnectFrame = QtWidgets.QFrame(self.centralwidget)
        self.ConnectFrame.setGeometry(QtCore.QRect(500, 20, 101, 91))
        self.ConnectFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ConnectFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ConnectFrame.setObjectName("ConnectFrame")
        self.ConnectionLabel = QtWidgets.QLabel(self.ConnectFrame)
        self.ConnectionLabel.setGeometry(QtCore.QRect(10, 10, 101, 16))
        self.ConnectionLabel.setObjectName("ConnectionLabel")
        self.ConnectButton = QtWidgets.QPushButton(self.ConnectFrame)
        self.ConnectButton.setGeometry(QtCore.QRect(10, 30, 75, 23))
        self.ConnectButton.setObjectName("ConnectButton")
        self.DisconnectButton = QtWidgets.QPushButton(self.ConnectFrame)
        self.DisconnectButton.setGeometry(QtCore.QRect(10, 60, 75, 23))
        self.DisconnectButton.setObjectName("DisconnectButton")
        self.CommandFrame = QtWidgets.QFrame(self.centralwidget)
        self.CommandFrame.setGeometry(QtCore.QRect(10, 19, 301, 91))
        self.CommandFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CommandFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CommandFrame.setObjectName("CommandFrame")
        self.CommandLabel = QtWidgets.QLabel(self.CommandFrame)
        self.CommandLabel.setGeometry(QtCore.QRect(10, 10, 81, 16))
        self.CommandLabel.setObjectName("CommandLabel")
        self.CommandTextInput = QtWidgets.QPlainTextEdit(self.CommandFrame)
        self.CommandTextInput.setGeometry(QtCore.QRect(10, 40, 281, 31))
        self.CommandTextInput.setObjectName("CommandTextInput")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.GPSLabel.setText(_translate("MainWindow", "GPS"))
        self.FPGALabel.setText(_translate("MainWindow", "FPGA"))
        self.ConnectionLabel.setText(_translate("MainWindow", "FPGA Connection"))
        self.ConnectButton.setText(_translate("MainWindow", "Connect"))
        self.DisconnectButton.setText(_translate("MainWindow", "Disconnect"))
        self.CommandLabel.setText(_translate("MainWindow", "Enter Command"))
